import Head from 'next/head';
import Link from 'next/Link'

export default function Nav({ data }) {
  console.log('data', data)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {data.map(d => <li key={d.category_id}><Link href={d.category_listing_page_url}>{d.category_name}</Link></li>)}
        </ul>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:5555/menu`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
